### ISSUE TITLE
请问 DoRes 这个 function type 用来做什么？

### ISSUE THREAD

**Issue by edte** [domechn/msg-pusher#4]
你好，我最近在读这个源码，但是有个地方我没有懂
![20201024-200220-419905786](https://user-images.githubusercontent.com/50194671/97081292-06047d00-1634-11eb-90a5-ad050c24578d.png)

请问这个 Sender 接口里的 do DoRes 参数有什么用？我看你用 wechat，email，sms 都实现了 这个接口，但是传递这个参数有什么用呢？我看你代码里写的都是，先判断 nil，然后直接调用了这个函数，email 接口甚至没有实现。

对应的测试文件也完全没有这个参数，那这个参数有何用？是出于什么目的设计的呢？

**Comment by domechn** [comment]
感谢阅读，可以看到 Send 这个函数只返回了 `error` 来告诉调用者是否发送成功，如果调用者想要获取到原始调用结果是没有办法的，比如阿里云短信接口的返回值。这时可以通过 `DoRes` 来对原始返回做一些处理，比如：
```
client.Send(msg, func(res interface{}){
    switch res.(type){
        case *sms.Response:
            // do some actions ....
    }
})
```

当然，这个接口也可以定义成 `Send(msg Message) interface{}, error` ，不过我个人理解，并不是所有 Sender 都需要关心原始返回值，比如 email，所以不把原始调用结果作为返回。

**Comment by domechn** [comment]
如果你后续有什么问题，或者想要交流的话，方便加我微信吗 `domchan0` ？
